name: Pull Request Validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write # This is required for Az CLI Login
  contents: read # This is required for actions/checkout

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v4

    - name: "Dependency Review"
      uses: actions/dependency-review-action@v4

  terraform-plan-poc:
    environment: poc
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.repository }}-poc

    steps:
      - uses: actions/checkout@v4

      - uses: frasermolyneux/actions/terraform-plan@main
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/poc.tfvars"
          backend-subscription-id: ${{ secrets.tf_backend_subscription_id }}
          backend-resource-group-name: ${{ secrets.tf_backend_resource_group_name }}
          backend-storage-account-name: ${{ secrets.tf_backend_storage_account_name }}
          backend-container-name: ${{ secrets.tf_backend_container_name }}
          backend-key: ${{ secrets.tf_backend_key }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}