# This workflow is used once a feature has been merged into main, it will perform lightweight CI and deploy to production.

name: Release to PoC

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

concurrency:
  group: ${{ github.workflow }}

jobs:
 terraform-plan-and-apply-poc:
    environment: poc
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.repository }}-poc

    steps:
      - uses: actions/checkout@v4

      - uses: frasermolyneux/actions/terraform-plan-and-apply@main
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/poc.tfvars"
          backend-subscription-id: ${{ secrets.tf_backend_subscription_id }}
          backend-resource-group-name: ${{ secrets.tf_backend_resource_group_name }}
          backend-storage-account-name: ${{ secrets.tf_backend_storage_account_name }}
          backend-container-name: ${{ secrets.tf_backend_container_name }}
          backend-key: ${{ secrets.tf_backend_key }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
